user_input1 = (input("What is your favorite animal: "))
print("You answered: " + user_input1)
user_input2 = (input("Why is this your favorite: "))
print("You answered: " + user_input2)
user_input3 = (input("What sound does the animal make? "))
print("You answered: " + user_input3)
user_input4 = (input("What do they eat? "))
print("You answered: " + user_input4)
print("You favorite animal was:" ,user_input1, "They are your favorite because:" ,user_input2, "They go:" ,user_input3, "They eat:" ,user_input4)