favorite_animal = (input("What is your favorite animal?\n>"))
print("You answered: " + favorite_animal)
why = (input("Why is this your favorite?\n>"))
print("You answered: " + why)
sound = (input("What sound does the animal make?\n>"))
print("You answered: " + sound)
food = (input("What do they eat? \n>"))
print("You answered: " + food)
location = (input("Where do they live?\n>"))
print("You said they live: " + location)
color = (input("What color are they?\n>"))
print("They are: " + color)
print("You favorite animal was " + favorite_animal + "\nThey are your favorite because " + why + "\nThey go " + sound + "\nThey eat " + food + "\nThey live " + location + "\nThey are " + color)
