answer = int(input("Give a whole number that is less than 9.\n"))
print(answer < 9)
answer2 = int(input("Give me a whole number that is greater than 8.\n"))
print(answer > 8)
answer3 = int(input("Give me a whole number that is greater than 2.\n"))
print(answer3 > 2)
answer3 = int(input("Give me a whole number equal to 5.\n"))
print(answer3 == 5)
answer5 = int(input("Give me a whole number greater than 3.\n"))
print(answer5 > 3)
answer6 = int(input("Give me a whole number that is less than 8, and greater than 1.\n"))
print(answer6 >1 and answer6 < 8)
answer7 = int(input("Give me a whole number that is greater that 2, and  less than 7.\n"))
print(answer7 > 2 and answer7 < 7)
answer8 = int(input("Give me a number that is not 3.\n"))
print(answer8 != 3)