#questions: once upon a time in a land called(noun) There lived a (noun) This (noun) liked the color blue because it was very (adjective)
# (noun's) favorite hobby was to (verb). One day (noun) invaded (1st noun response) 
#person was (emotion) because they could no longer eat lobster
#madlib pseudocode: ask player several questions (input functions)
#compile all of the players responses and print them in a summary
homecountry = input("enter a place: \n>")
protagonist = input("enter a name: \n>")
blueadj = input("enter an adjective: \n>")
hobby = input("enter a verb: \n>")
enemycountry = input("enter a place: \n>")
emo = input("enter an emotion: \n>")
enemyally = input("enter a place: \n>")
resource = input("enter a resource: \n>")
lostverb = input("enter a verb: \n>")
print("Once upon a time in a land called " + homecountry + " There lived a person named " + protagonist + ".\n>This " + protagonist + " liked the color blue because it was very " + blueadj + "\n>" + protagonist + "'s favorite hobby was to " + hobby + "\n> One day " + enemycountry + " invaded " + homecountry + "\n>" + protagonist + " was " + emo + " because they were no longer able to eat lobster\n" + enemycountry + " called on their military ally of " + enemyally + "The addition of " + enemyally + " into the war caused " + homecountry + " to lose.\nThe peace treaty between " + homecountry + " and " + enemycountry + " resulted in " + homecountry + " ceding lots of " + resource + " to " + enemycountry + "\nThe lack of " + resource + " meant that " + protagonist + " could no longer " + lostverb)