#questions: once upon a time in a land called(noun) There lived a (noun) This (noun) liked the color blue because it was very (adjective)
# (noun's) favorite hobby was to (verb). One day (noun) invaded (1st noun response) 
#person was conscripted into the army and they were (emotion) because they could no longer eat (food)
#madlib pseudocode: ask player several questions (input functions)
#compile all of the players responses and print them in a summary
homecountry = input("enter a noun: \n>")
protagonist = input("enter a noun: \n>")
blueadj = input("enter an adjective: \n>")
hobby = input("enter a verb: \n>")
enemycountry = input("enter a noun: \n>")
emo = input("enter an emotion: \n>")
print("Once upon a time in a land called " + homecountry + " There lived a " + protagonist + ".\n>This " + protagonist + " liked the color blue because it was very " + blueadj + "\n>" + protagonist + "'s favorite hobby was to " + hobby + "\n> One day " + enemycountry + " invaded " + homecountry + "\n>" + protagonist + " was " + emo + " because they were no longer able to eat lobster")